export const FETCH_ACTIVITIES_PENDING = "FETCH_ACTIVITIES_PENDING"
export const FETCH_ACTIVITIES_REJECTED = "FETCH_ACTIVITIES_REJECTED"
export const FETCH_ACTIVITIES_FULFILLED = "FETCH_ACTIVITIES_FULFILLED"
