export const SEARCH_REPOSITORIES_PENDING = "SEARCH_REPOSITORIES_PENDING"
export const SEARCH_REPOSITORIES_REJECTED = "SEARCH_REPOSITORIES_REJECTED"
export const SEARCH_REPOSITORIES_FULFILLED = "SEARCH_REPOSITORIES_FULFILLED"
